# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KIjok9T2PBuwVCE18WhvWTljl4jXcaxD
"""

n1 = float(input("Escolha um número >>"))
escolha = input(">>")
n2 = float(input("Escolha um número >>"))


def calc(n1,n2):
 if escolha == '+':
     print(n1+n2)
 elif escolha == '-':
     print(n1-n2)
 elif escolha == '*':
     print(n1*n2)
 elif escolha == "/":
     print(n1/n2)
 else:
  print("Digite outra fórmula válida.")


calc(n1,n2)